### ISSUE TITLE
request some feature enhancements

### ISSUE THREAD

**Issue by muralikodali** [WebReflection/tmd#1]
on code lines color backgroung is extended to the end of terminal.
- it will look better,  if text is limited to the border of text.
- an option to change background color

![screenshot_20210405141609](https://user-images.githubusercontent.com/11482766/113556298-e5484680-9619-11eb-8fcb-e55bb5fb6765.png)

**Comment by WebReflection** [comment]
> it will look better, if text is limited to the border of text.

I disagree, because multiple lines with different length per line would look overly awkward ... I'd rather make the header full line length too instead.

> an option to change background color

I am not sure in which environment you see it that way ... I see it different color and while I agree your color schema looks awful, I am not sure I should start parsing all possible arguments to change all possible things as that would drop the KISS approach of this helper.

Any idea might be welcome though, thanks.

**Comment by muralikodali** [comment]
thanks for your reply
